
###Test 1###
GET http://localhost:8000/api/books 

###Test 2a###
GET http://localhost:8000/api/books?q=clean 

###Test 2b###
GET http://localhost:8000/api/books?limit=2      

###Test 3###
POST http://localhost:8000/api/books 

Content-Type: application/json 
  
{ "title":"Refactoring", "author":"Martin Fowler", "year":2018 } 

###Test 4a###
PUT    http://localhost:8000/api/books/1   { "genre": "Software Craftsmanship" }   

###Test 4b###
DELETE http://localhost:8000/api/books/2  


